### ISSUE TITLE
Add list of files to be published on npm

### ISSUE THREAD

**Issue by easingthemes** [adobe/aio-lib-core-errors#12]
### Expected Behaviour
Only core files are published as npm package
Add list of files in package.json
```
"files": []
```
### Actual Behaviour
All files are published as npm package.
```
Unpacked Size
382 kB
```
This creates false assumption of a big package and probably will stop a lot of people from using it in client side JS.
Core files are minimal, size will drop x 100

**Comment by meryllblanchet** [comment]
Thanks for raising the issue @easingthemes ! 
Assigning to @shazron for feedback - your PR is welcome.

**Comment by shazron** [comment]
PR #13
