### ISSUE TITLE
toJSON output not consistent with actual error object shape

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-lib-core-errors#3]
### Expected Behaviour

Fields returned by toJSON() should match the actual error object shape

### Actual Behaviour
toJSON returns `e.sdk.details` and `e.sdk.name` while the actual fields in the error object are retrieved by `e.sdkDetails` and `e.name`

This incoherence might confuse the end user who would fail to access the fields on the error object based on what he sees in the logs (if the error was logged using JSON.stringify).

**Comment by moritzraho** [comment]
@shazron wdyt?

**Comment by shazron** [comment]
@moritzraho sounds good!
